<a href="https://colab.research.google.com/github/suryavamshi866/Next_Word_Prediction/blob/main/Next_Word_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


In [3]:
tokenizer=Tokenizer()

In [4]:
tokenizer.fit_on_texts([faqs])

In [5]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [6]:
tokenizer.word_counts

OrderedDict([('about', 2),
             ('the', 69),
             ('program', 11),
             ('what', 14),
             ('is', 18),
             ('course', 12),
             ('fee', 5),
             ('for', 10),
             ('data', 5),
             ('science', 4),
             ('mentorship', 3),
             ('dsmp', 1),
             ('2023', 1),
             ('follows', 2),
             ('a', 19),
             ('monthly', 5),
             ('subscription', 6),
             ('model', 2),
             ('where', 6),
             ('you', 37),
             ('have', 18),
             ('to', 27),
             ('make', 7),
             ('payments', 3),
             ('of', 19),
             ('rs', 6),
             ('799', 3),
             ('month', 5),
             ('total', 3),
             ('duration', 3),
             ('7', 4),
             ('months', 3),
             ('so', 6),
             ('becomes', 1),
             ('5600', 4),
             ('approx', 1),
             ('syllabus', 

In [12]:
input_sequences=[]
for sentence in faqs.split('\n'):
  print(sentence)
  print(tokenizer.texts_to_sequences([sentence]))
  #for every sentence it creates an array
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])


About the Program
[[93, 1, 13]]
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
[[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]]
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
[[1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70, 45]]
What is the total duration of the course?
[[11, 7, 1, 71, 72, 6, 1, 12]]
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
[[1, 71, 72, 6, 1, 12, 7, 54, 73, 32, 1, 71, 12, 42, 149, 70, 54, 31, 55, 150]]
What is the syllabus of the mentorship program?
[[11, 7, 1, 96, 6, 1, 68, 13]]
We will be covering the following modules:
[[27, 9, 19, 151, 1, 152, 153]]
Python Fundamentals
[[97, 154]]
Python libraries for Data Science
[[97, 155, 15, 43, 53]]
Data Analysis
[[43, 156]]
SQL for Data Science
[[157, 15, 43, 53]]
Maths for Machine Learning
[[158, 15, 159, 74]]
ML Algorithms
[[98, 160]]
Practical ML
[[161, 98]]
MLOPs

In [13]:
input_sequences[0]

[93, 1]

In [14]:
max_len=max([len(x) for x in input_sequences])

In [15]:
from keras.preprocessing.sequence import pad_sequences

In [16]:
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [17]:
x=padded_input_sequences[:,:-1]
#taking all values except the last value

In [18]:
y=padded_input_sequences[:,-1]
#taking only the last values

In [19]:
print(x,y)

[[  0   0   0 ...   0   0  93]
 [  0   0   0 ...   0  93   1]
 [  0   0   0 ...   0   0  11]
 ...
 [  0   0   0 ...   0 279  18]
 [  0   0   0 ... 279  18 280]
 [  0   0   0 ...  18 280 281]] [  1  13   7   1  12  42  15  43  53  68  13 147 148  12  94   5  44  29
  95  30   2   8   4  26  44  69   6  31  70  45   7   1  71  72   6   1
  12  71  72   6   1  12   7  54  73  32   1  71  12  42 149  70  54  31
  55 150   7   1  96   6   1  68  13   9  19 151   1 152 153 154 155  15
  43  53 156  15  43  53  15 159  74 160  98  99  10 163   1 164  96  76
  77 100  33  14 165  33  43  53  68  13 166 101  74  20 102  19   5  78
   6  21  13 102  20 101  74 167  56  46   5  78   6  21 168 169  22   3
 104   5 105  34   9   3  47   5 106   6   1  34  16  35  17  56 170  32
 107  22   2 104   5  34   2  10 171 172  20  57   1 106  10   3 173   1
 108 174  21  58 176   4  79  45  59  45 109 177   6   1  12  77 178  58
  60 179 180 181 182 183 184 185   7   1 109  72   6  16   1 105  17  16
   1 

In [24]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)
#as the one hot encoding starts from 0 thats why we used tokenizer.word_index

In [34]:
x.shape

(863, 56)

In [25]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
#Below the starting of the index starts with 0 but we dont have anything like that in our word_index we just use it because one hot encoding starts from 0

In [31]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [32]:
len(y[0])

283

In [ ]:
 x

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], dtype=int32)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [36]:
model=Sequential()
model.add(Embedding(input_dim=283,output_dim=100,input_length=56))
#input_dim = vocabulary size
#Size of each word’s embedding vector
#Length of each input sequence (number of tokens per sentence).

#If a sentence has fewer than 56 words → it’s padded with zeros.

model.add(LSTM(150))
model.add(Dense(283,activation='softmax'))
model.build(input_shape=(None,56))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 283)            │        42,733 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [38]:
model.fit(x,y,epochs=100)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.0513 - loss: 5.5596
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0657 - loss: 5.1021
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0807 - loss: 5.0106
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0850 - loss: 4.9227
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0794 - loss: 4.8971
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0881 - loss: 4.7681
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0822 - loss: 4.7195
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1298 - loss: 4.4181
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1607 - loss: 4.2278
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1756 - loss: 4.0736
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2103 - loss: 3.8300
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy:

In [41]:
import time
import numpy as np

In [42]:
text='mail'
for i in range(10):

  #tokenize padding predict
  token_text=tokenizer.texts_to_sequences([text])[0]
  padded_token_text=pad_sequences([token_text],maxlen=56,padding='pre')
  print(padded_token_text)

  pos=np.argmax(model.predict(padded_token_text))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+' '+word
      print(text)
      time.sleep(2)


[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0 61]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
mail this
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0 61 21]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
mail this google
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0 61 21 58]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
mail this google sheet
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  61  21
   58 176]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
mail this google sheet to
[[  0   0